# Generated by Django 5.2.7 on 2025-10-14 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_booking_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="people",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ]
            ),
        ),
    ]
