# Generated by Django 5.2.7 on 2025-10-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_booking_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
