# Generated by Django 5.2.7 on 2025-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_booking_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="room_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
