# Generated by Django 5.2.7 on 2025-10-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_booking_is_approved_booking_room_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="mobile_number",
        ),
    ]
